'use strict';

module.exports = {
	app: {
		title: 'sun',
		description: 'boss',
		keywords: 'raj'
	},
	port: process.env.PORT || 3000,
	templateEngine: 'swig',
	sessionSecret: 'MEAN',
	sessionCollection: 'sessions',
	assets: {
		lib: {
			css: [
				'public/lib/bootstrap/dist/css/bootstrap.css',
				'public/lib/bootstrap/dist/css/bootstrap-theme.css',
                'https://cdnjs.cloudflare.com/ajax/libs/spectrum/1.6.1/spectrum.min.css',
                'public/lib/font-awesome/css/font-awesome.min.css',
                'public/lib/textAngular-1.4.2/dist/textAngular.css',
                'public/lib/angular-gridster/dist/angular-gridster.min.css',
                'public/lib/angular-gridster/demo/common/gstyle.css',
                'public/lib/angular-gridster/demo/main/g_style.css',
                'public/lib/supersized/slideshow/css/supersized.css',
                'public/lib/FroalaWysiwygEditor/css/froala_editor.min.css',
                'public/lib/FroalaWysiwygEditor/css/froala_content.css',
                'public/lib/FroalaWysiwygEditor/css/froala_style.css',
                'public/lib/angular-splash/splash.css',
                'public/lib/styles.css',
                'public/lib/style.css',
                'public/lib/spectrum/spectrum.css',
                'public/lib/jquery-box-slider-master/css/style.css',
                'public/lib/slick.js/slick/slick.css',
                'public/lib/angular-slider/slideviewer.css',
                'public/lib/angular-tags/dist/angular-tags-0.2.10.css',
                'public/lib/slick.js/slick/slick-theme.css',
            ],
			js: [
                '//code.jquery.com/jquery-1.11.0.min.js',
                'https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js',
                'http://cdnjs.cloudflare.com/ajax/libs/gsap/1.17.0/TweenMax.min.js',
                '//code.jquery.com/jquery-migrate-1.2.1.min.js',
                'public/lib/ng-file-upload-shim/ng-file-upload-shim(.min).js',
                'public/lib/angular/angular.min.js',
                'public/lib/angular-animate/angular-animate.js',
                'public/lib/angular-touch/angular-touch.js',
                'public/lib/textAngular/dist/textAngular-rangy.min.js',
                'public/lib/textAngular-1.4.2/dist/textAngular-sanitize.js',
                'public/lib/ng-file-upload-shim/ng-file-upload(.min).js',
                'public/lib/textAngular/dist/textAngular.js',
                'public/lib/textAngular/dist/textAngularSetup.js',
                'public/lib/FroalaWysiwygEditor/js/froala_editor.min.js',
                'public/lib/angular-spectrum-colorpicker/dist/angular-spectrum-colorpicker.min.js',
                'public/lib/angular-froala/src/angular-froala.js',
                'public/lib/angular-ui-router/release/angular-ui-router.js',
				'public/lib/angular-resource/angular-resource.js',
                'public/lib/ngDraggable/ngDraggable.js',
                'public/lib/FroalaWysiwygEditor/js/plugins/tables.min.js'      ,
                'public/lib/FroalaWysiwygEditor/js/plugins/video.min.js'       ,
                'public/lib/FroalaWysiwygEditor/js/plugins/block_styles.min.js' ,
                'public/lib/FroalaWysiwygEditor/js/plugins/colors.min.js'      ,
                'public/lib/FroalaWysiwygEditor/js/plugins/media_manager.min.js',
                'public/lib/FroalaWysiwygEditor/js/plugins/lists.min.js'        ,
                'public/lib/FroalaWysiwygEditor/js/plugins/font_family.min.js'  ,
                'public/lib/FroalaWysiwygEditor/js/plugins/font_size.min.js'    ,
                'public/lib/FroalaWysiwygEditor/js/plugins/file_upload.min.js'  ,
                'public/lib/FroalaWysiwygEditor/js/plugins/urls.min.js'         ,
                'public/lib/FroalaWysiwygEditor/js/plugins/fullscreen.min.js',
                'public/lib/FroalaWysiwygEditor/js/plugins/inline_styles.min.js',
                'public/lib/FroalaWysiwygEditor/js/plugins/char_counter.min.js' ,
                'public/lib/FroalaWysiwygEditor/js/plugins/entities.min.js' ,
                'public/lib/angular-clear-input/angular-clear-input.min.js',
                'public/lib/ng-facebook/ngFacebook.js',
                'public/lib/classie/classie.js',
                'public/lib/spectrum/spectrum.js',
                'public/lib/ng-file-upload/ng-file-upload.min.js',
                '//cdn.jsdelivr.net/headroomjs/0.7.0/headroom.min.js',
                '//cdnjs.cloudflare.com/ajax/libs/headroom/0.7.0/angular.headroom.min.js',
                'public/lib/angular-cookies/angular-cookies.js',
                'public/lib/angular-scroll/angular-scroll.min.js',
                'public/lib/angular-scrollto/angular-scrollto.js',
                'public/lib/jquery-box-slider-master/js/box-slider-all.jquery.min.js',
                'public/lib/angular-splash/splash.js',
                'public/lib/angular-ui-utils/ui-utils.js',
                'public/lib/jquery-box-slider-master/test/spec/box-slider.js',
                'public/lib/angular-slider/slideviewer.js',
                'public/lib/supersized/slideshow/js/supersized.3.2.7.js',
                'public/lib/supersized/slideshow/theme/supersized.shutter.min.js',
				'public/lib/angular-bootstrap/ui-bootstrap-tpls.js',
                'public/lib/angular-utils-pagination/dirPagination.js',
                'public/lib/angular-tags/dist/angular-tags-0.2.10-tpls.js',
                'public/lib/angular-gridster/dist/angular-gridster.min.js',
                '//cdn.jsdelivr.net/jquery.slick/1.5.5/slick.min.js'
			    ]
		},
		css: [
			'public/modules/**/css/*.css'
		     ],
		js: [
			'public/config.js',
			'public/application.js',
			'public/modules/*/*.js',
			'public/modules/*/*[!tests]*/*.js'
		     ],
		tests: [
			'public/lib/angular-mocks/angular-mocks.js',
			'public/modules/*/tests/*.js'
		     ]
	        }
           };
